/**
 * Standalone MCP server (stdio transport) - the "full read/write" Claude
 * Desktop connector from the Phase 1 answer, for a traditional mcpServers
 * config entry. Runs as its own local process, reads/writes the exact same
 * SQLite file (WAL mode) the Electron app uses, and never talks to a
 * network - this is a local pipe between Claude and the on-disk data, not
 * an AI-extraction feature calling out to an API.
 *
 * Must run as the Electron binary itself in ELECTRON_RUN_AS_NODE mode, NOT
 * plain `node`/`tsx`: better-sqlite3 here is compiled against Electron's
 * Node ABI (see package.json postinstall), so this needs to actually be
 * that same binary to load it. Claude Desktop's config (generated by
 * registerIpc.ts's MCP_GET_CONNECTOR_INFO handler) points `command` at
 * process.execPath directly - the running app's own .exe, dev or packaged -
 * with that env var set, so no separate Node.js install is required on the
 * user's machine. `npm run mcp` (scripts/run-mcp.js) does the same thing
 * for manual/dev use from a terminal.
 *
 * The actual tool set lives in src/mcp/tools.ts, shared with the in-process
 * HTTP server the Electron app hosts (src/main/mcp/httpServer.ts) for the
 * paste-a-URL-into-Claude-Desktop connector method.
 */
import { join } from 'path'
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js'
import { runMigrations } from '@main/db/migrate'
import { migrateLegacyAppDataDirIfNeeded } from '@shared/paths'
import { registerMcpTools } from './tools'

async function main(): Promise<void> {
  migrateLegacyAppDataDirIfNeeded()
  // In ELECTRON_RUN_AS_NODE mode there's no `app` module (no Electron
  // runtime bootstrap), so this process can't call app.isPackaged to know
  // whether drizzle/ is a relative sibling (dev) or a resourcesPath sibling
  // of app.asar (packaged, per electron-builder.yml's extraResources) -
  // the spawning process (registerIpc.ts, a real Electron process that DOES
  // know) resolves the right path and passes it via this env var instead.
  runMigrations(process.env.RENVOR_DRIZZLE_DIR ?? join(__dirname, '../../drizzle'))

  const server = new McpServer({ name: 'renvor', version: '1.0.0' })
  registerMcpTools(server)

  const transport = new StdioServerTransport()
  await server.connect(transport)
  console.error('Renvor MCP server ready (stdio).')
}

main().catch((error) => {
  console.error('MCP server error:', error)
  process.exit(1)
})
